// Code generated by mockery v2.23.4. DO NOT EDIT.

package auth

import (
	model "github.com/kevindharmawan/saas-backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockValidationRepository is an autogenerated mock type for the ValidationRepository type
type MockValidationRepository struct {
	mock.Mock
}

type MockValidationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidationRepository) EXPECT() *MockValidationRepository_Expecter {
	return &MockValidationRepository_Expecter{mock: &_m.Mock}
}

// ValidateToken provides a mock function with given fields: token
func (_m *MockValidationRepository) ValidateToken(token string) (int64, *model.AppError) {
	ret := _m.Called(token)

	var r0 int64
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(string) (int64, *model.AppError)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) *model.AppError); ok {
		r1 = rf(token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// MockValidationRepository_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockValidationRepository_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - token string
func (_e *MockValidationRepository_Expecter) ValidateToken(token interface{}) *MockValidationRepository_ValidateToken_Call {
	return &MockValidationRepository_ValidateToken_Call{Call: _e.mock.On("ValidateToken", token)}
}

func (_c *MockValidationRepository_ValidateToken_Call) Run(run func(token string)) *MockValidationRepository_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockValidationRepository_ValidateToken_Call) Return(_a0 int64, _a1 *model.AppError) *MockValidationRepository_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockValidationRepository_ValidateToken_Call) RunAndReturn(run func(string) (int64, *model.AppError)) *MockValidationRepository_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidationRepository creates a new instance of MockValidationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidationRepository {
	mock := &MockValidationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
