// Code generated by mockery v2.23.4. DO NOT EDIT.

package auth

import (
	model "github.com/kevindharmawan/saas-backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function with given fields: authId
func (_m *MockTokenRepository) CreateToken(authId int64) (*model.Token, *model.AppError) {
	ret := _m.Called(authId)

	var r0 *model.Token
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(int64) (*model.Token, *model.AppError)); ok {
		return rf(authId)
	}
	if rf, ok := ret.Get(0).(func(int64) *model.Token); ok {
		r0 = rf(authId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) *model.AppError); ok {
		r1 = rf(authId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// MockTokenRepository_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockTokenRepository_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - authId int64
func (_e *MockTokenRepository_Expecter) CreateToken(authId interface{}) *MockTokenRepository_CreateToken_Call {
	return &MockTokenRepository_CreateToken_Call{Call: _e.mock.On("CreateToken", authId)}
}

func (_c *MockTokenRepository_CreateToken_Call) Run(run func(authId int64)) *MockTokenRepository_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockTokenRepository_CreateToken_Call) Return(_a0 *model.Token, _a1 *model.AppError) *MockTokenRepository_CreateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepository_CreateToken_Call) RunAndReturn(run func(int64) (*model.Token, *model.AppError)) *MockTokenRepository_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: token
func (_m *MockTokenRepository) ValidateToken(token string) (int64, *model.AppError) {
	ret := _m.Called(token)

	var r0 int64
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(string) (int64, *model.AppError)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) *model.AppError); ok {
		r1 = rf(token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// MockTokenRepository_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockTokenRepository_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenRepository_Expecter) ValidateToken(token interface{}) *MockTokenRepository_ValidateToken_Call {
	return &MockTokenRepository_ValidateToken_Call{Call: _e.mock.On("ValidateToken", token)}
}

func (_c *MockTokenRepository_ValidateToken_Call) Run(run func(token string)) *MockTokenRepository_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenRepository_ValidateToken_Call) Return(_a0 int64, _a1 *model.AppError) *MockTokenRepository_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepository_ValidateToken_Call) RunAndReturn(run func(string) (int64, *model.AppError)) *MockTokenRepository_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
