// Code generated by mockery v2.23.4. DO NOT EDIT.

package user

import (
	model "github.com/kevindharmawan/saas-backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: _a0
func (_m *MockUserService) CreateUser(_a0 *model.User) (*model.User, *model.AppError) {
	ret := _m.Called(_a0)

	var r0 *model.User
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(*model.User) (*model.User, *model.AppError)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*model.User) *model.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.User) *model.AppError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// MockUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - _a0 *model.User
func (_e *MockUserService_Expecter) CreateUser(_a0 interface{}) *MockUserService_CreateUser_Call {
	return &MockUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", _a0)}
}

func (_c *MockUserService_CreateUser_Call) Run(run func(_a0 *model.User)) *MockUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.User))
	})
	return _c
}

func (_c *MockUserService_CreateUser_Call) Return(_a0 *model.User, _a1 *model.AppError) *MockUserService_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_CreateUser_Call) RunAndReturn(run func(*model.User) (*model.User, *model.AppError)) *MockUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: id
func (_m *MockUserService) DeleteUser(id int64) *model.AppError {
	ret := _m.Called(id)

	var r0 *model.AppError
	if rf, ok := ret.Get(0).(func(int64) *model.AppError); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AppError)
		}
	}

	return r0
}

// MockUserService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - id int64
func (_e *MockUserService_Expecter) DeleteUser(id interface{}) *MockUserService_DeleteUser_Call {
	return &MockUserService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", id)}
}

func (_c *MockUserService_DeleteUser_Call) Run(run func(id int64)) *MockUserService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockUserService_DeleteUser_Call) Return(_a0 *model.AppError) *MockUserService_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_DeleteUser_Call) RunAndReturn(run func(int64) *model.AppError) *MockUserService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByAuthId provides a mock function with given fields: authId
func (_m *MockUserService) GetUserByAuthId(authId string) (*model.User, *model.AppError) {
	ret := _m.Called(authId)

	var r0 *model.User
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(string) (*model.User, *model.AppError)); ok {
		return rf(authId)
	}
	if rf, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = rf(authId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *model.AppError); ok {
		r1 = rf(authId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// MockUserService_GetUserByAuthId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByAuthId'
type MockUserService_GetUserByAuthId_Call struct {
	*mock.Call
}

// GetUserByAuthId is a helper method to define mock.On call
//   - authId string
func (_e *MockUserService_Expecter) GetUserByAuthId(authId interface{}) *MockUserService_GetUserByAuthId_Call {
	return &MockUserService_GetUserByAuthId_Call{Call: _e.mock.On("GetUserByAuthId", authId)}
}

func (_c *MockUserService_GetUserByAuthId_Call) Run(run func(authId string)) *MockUserService_GetUserByAuthId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserService_GetUserByAuthId_Call) Return(_a0 *model.User, _a1 *model.AppError) *MockUserService_GetUserByAuthId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetUserByAuthId_Call) RunAndReturn(run func(string) (*model.User, *model.AppError)) *MockUserService_GetUserByAuthId_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByCustomerId provides a mock function with given fields: customerId
func (_m *MockUserService) GetUserByCustomerId(customerId string) (*model.User, *model.AppError) {
	ret := _m.Called(customerId)

	var r0 *model.User
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(string) (*model.User, *model.AppError)); ok {
		return rf(customerId)
	}
	if rf, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = rf(customerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *model.AppError); ok {
		r1 = rf(customerId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// MockUserService_GetUserByCustomerId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByCustomerId'
type MockUserService_GetUserByCustomerId_Call struct {
	*mock.Call
}

// GetUserByCustomerId is a helper method to define mock.On call
//   - customerId string
func (_e *MockUserService_Expecter) GetUserByCustomerId(customerId interface{}) *MockUserService_GetUserByCustomerId_Call {
	return &MockUserService_GetUserByCustomerId_Call{Call: _e.mock.On("GetUserByCustomerId", customerId)}
}

func (_c *MockUserService_GetUserByCustomerId_Call) Run(run func(customerId string)) *MockUserService_GetUserByCustomerId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserService_GetUserByCustomerId_Call) Return(_a0 *model.User, _a1 *model.AppError) *MockUserService_GetUserByCustomerId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetUserByCustomerId_Call) RunAndReturn(run func(string) (*model.User, *model.AppError)) *MockUserService_GetUserByCustomerId_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: email
func (_m *MockUserService) GetUserByEmail(email string) (*model.User, *model.AppError) {
	ret := _m.Called(email)

	var r0 *model.User
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(string) (*model.User, *model.AppError)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *model.AppError); ok {
		r1 = rf(email)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// MockUserService_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUserService_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockUserService_Expecter) GetUserByEmail(email interface{}) *MockUserService_GetUserByEmail_Call {
	return &MockUserService_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", email)}
}

func (_c *MockUserService_GetUserByEmail_Call) Run(run func(email string)) *MockUserService_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserService_GetUserByEmail_Call) Return(_a0 *model.User, _a1 *model.AppError) *MockUserService_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetUserByEmail_Call) RunAndReturn(run func(string) (*model.User, *model.AppError)) *MockUserService_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function with given fields: id
func (_m *MockUserService) GetUserById(id int64) (*model.User, *model.AppError) {
	ret := _m.Called(id)

	var r0 *model.User
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(int64) (*model.User, *model.AppError)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *model.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) *model.AppError); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// MockUserService_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type MockUserService_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - id int64
func (_e *MockUserService_Expecter) GetUserById(id interface{}) *MockUserService_GetUserById_Call {
	return &MockUserService_GetUserById_Call{Call: _e.mock.On("GetUserById", id)}
}

func (_c *MockUserService_GetUserById_Call) Run(run func(id int64)) *MockUserService_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockUserService_GetUserById_Call) Return(_a0 *model.User, _a1 *model.AppError) *MockUserService_GetUserById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetUserById_Call) RunAndReturn(run func(int64) (*model.User, *model.AppError)) *MockUserService_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: _a0
func (_m *MockUserService) UpdateUser(_a0 *model.User) (*model.User, *model.AppError) {
	ret := _m.Called(_a0)

	var r0 *model.User
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(*model.User) (*model.User, *model.AppError)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*model.User) *model.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.User) *model.AppError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// MockUserService_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserService_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - _a0 *model.User
func (_e *MockUserService_Expecter) UpdateUser(_a0 interface{}) *MockUserService_UpdateUser_Call {
	return &MockUserService_UpdateUser_Call{Call: _e.mock.On("UpdateUser", _a0)}
}

func (_c *MockUserService_UpdateUser_Call) Run(run func(_a0 *model.User)) *MockUserService_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.User))
	})
	return _c
}

func (_c *MockUserService_UpdateUser_Call) Return(_a0 *model.User, _a1 *model.AppError) *MockUserService_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_UpdateUser_Call) RunAndReturn(run func(*model.User) (*model.User, *model.AppError)) *MockUserService_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
